### ISSUE TITLE
How to train on CUB

### ISSUE THREAD

**Issue by Blackpinkup** [chou141253/FGVC-PIM#15]
Thanks for your great job! I have browsed your code and I found that the data is read in through the ImageDataset class, but it does not seem to fit the original format of the CUB dataset. Did you change the format of the original CUB dataset when you performed your experiments, and if so, can you please tell me how you did it?
![1](https://user-images.githubusercontent.com/58927039/163707139-918183c0-8482-40b2-a0d8-733fea4a0435.png)

**Comment by Blackpinkup** [comment]
I tried to write my own dataloader to solve my problem, here is the link of my project. https://github.com/Blackpinkup/FGVC-PIM

**Comment by OhJackHu** [comment]
Hi, bro, How can I use the downloaded pre-training weight instead of downloading the pre-training weight myself during training. I used the following code but reported an error:
self.extractor = timm.create_model('swin_large_patch4_window12_384_in22k', pretrained=False)
self.extractor = load_model_weights(self.extractor, './swin_large_patch4_window12_384_in22k.pth')

Traceback (most recent call last):
  File "train.py", line 400, in <module>
    train_loader, test_loader, model, optimizer, schedule = set_environment(args)
  File "train.py", line 97, in set_environment
    model = SwinVit12(
  File "/home/pengtl/jackhu/FGVC-PIM-master/models/SwinVit12.py", line 235, in __init__
    self.extractor = load_model_weights(self.extractor, "/home/pengtl/jackhu/swin_large_patch4_window12_384_22k.pth")
  File "/home/pengtl/jackhu/FGVC-PIM-master/models/SwinVit12.py", line 16, in load_model_weights
    if key in state['state_dict']:
KeyError: 'state_dict'

**Comment by Blackpinkup** [comment]
@OhJackHu I met the same problem. If you want to download pretrained model in C drive, then you have to modify timm folder to load your pretrianed model. But the simplest solution it to put your pretrained model in C drive to to replace torch hub. The path should be torch/hub/checkpoint.

**Comment by Blackpinkup** [comment]
I solved my problem by adding my own dataloader for CUB like datasets, hope my project can help you. https://github.com/Blackpinkup/FGVC-PIM
